# Site settings
title: Foundry-Matrix
email: Foundry@Matrix.com
description: > # this means to ignore newlines until "baseurl:"
  The fantastic four have met to conquer the world using their newly found coding skills. watch out
baseurl: "/fmblog" # the subpath of your site, e.g. /blog/
url: "http://foundry-matrix.github.io/fmblog/" # the base hostname & protocol for your site
twitter_username: founderscoders
github_username:  foundy-matrix

# Build settings
markdown: kramdown
